### ISSUE TITLE
Sample request: Saga

### ISSUE THREAD

**Issue by cretz** [temporalio/samples-dotnet#33]
### Describe the solution you'd like

Basically a simple saga sample following principles in other SDKs and outlined at https://temporal.io/blog/compensating-actions-part-of-a-complete-breakfast-with-sagas and https://temporal.io/blog/saga-pattern-made-easy

**Comment by aboelkassem** [comment]
Hi @cretz 
I have created a very basic sample for Saga pattern here https://github.com/aboelkassem/temporal-saga-dotnet
please let me know if it satisfies the implementation guide to be added to your samples

It basically follows up [saga sample in typescript](https://github.com/temporalio/samples-typescript/tree/main/saga)

**Comment by cretz** [comment]
Sure! Feel free to submit a PR. It looks like there were many things added such as having saga as a separate class, compensation complete/error callbacks, not log-then-swallowing compensation errors, etc. I think for a simple example we can just have the workflow maintain a set of compensations it loops over in reverse on error to be almost exactly like the TypeScript one.

**Comment by aboelkassem** [comment]
Thanks @cretz for allowing me to contribute
please check my PR https://github.com/temporalio/samples-dotnet/pull/46 and let me know your thoughts
