### ISSUE TITLE
[Feature Request] mTLS sample with explanations how to connect to Temporal Cloud

### ISSUE THREAD

**Issue by cgillum** [temporalio/samples-dotnet#5]
Basically, the same thing as described in this closed issue: https://github.com/temporalio/features/issues/89.

The README makes brief mention of TLS but there's a need for more specific instructions for how to connect to Temporal Cloud. I have a Temporal Cloud instance but so far, I haven't been able to get a Temporal client to connect to it successfully.

**Comment by cretz** [comment]
I will work on this example shortly.
