### ISSUE TITLE
[Feature Request] Sample Code to use TemporalClient.StartWorkflowAsync(string workflow, IReadOnlyCollection<object?> args, WorkflowOptions options)

### ISSUE THREAD

**Issue by canonw** [temporalio/samples-dotnet#61]
### Is your feature request related to a problem? Please describe.

I am trying figure out how to use the above method.  I have problem trying to figure out proper value for second paramater _args_

https://github.com/temporalio/sdk-dotnet/blob/1.0.0/src/Temporalio/Client/TemporalClient.Workflow.cs#L50-L51

All existing sample use only overloaded method
https://github.com/temporalio/sdk-dotnet/blob/1.0.0/src/Temporalio/Client/TemporalClient.Workflow.cs#L38-L39

which rely on the first parameter of Expression type to derive the _args_ value.

In my case, using Expression type parameter is not doable.   The running application does not have the activity interface defined.  

### Describe the solution you'd like

I see two possible solution
1. A separate project to demonstrate how to define args for a given workflow name
2. Document to explain how to derived the args using the _string workflow_ parameter

**Comment by cretz** [comment]
> I have problem trying to figure out proper value for second paramater args

Can you clarify the problem you're hitting a bit more here? Simply calling `await myClient.StartWorkflowAsync("my-workflow-name", new object[] { new MyParamType() }, ...)` should work just fine.

**Comment by canonw** [comment]
Thanks.  The sample snippet is sufficient.   The snippet suggests the value is workflow specific.   And running instance doesn't need any.
